version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: pracownia
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - DB_NAME=pracownia
      - JWT_SECRET=supersecret
      - PORT=3000
      - EMAIL_LOGIN=mail
      - EMAIL_PASSWORD=pass

  client:
    build:
      context: ./client
    depends_on:
      - backend
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production

volumes:
  db_data:
